name: Deploy Frontend

on:
  push:
    paths:
      - "frontend/**"
    tags:
      - "*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Deploy Frontend for ${{ github.ref_name }}
        run: |
          cd frontend/
          #echo "${{ secrets.FRONTEND_ENV }}" > .env.prod
          cp .env.example .env.prod
          #export project_name=${{ secrets.FRONTEND_NAME }}
          export project_name= temp_email_pages
          pnpm install --no-frozen-lockfile
          #export frontend_branch=${{ secrets.FRONTEND_BRANCH }}
          export frontend_branch=production
          if [ -n "$frontend_branch" ]; then
            echo "Deploying branch $frontend_branch"
            pnpm run deploy:actions --project-name=$project_name
          else
            echo "Deploying branch prodcution"
            pnpm run deploy --project-name=$project_name
          fi
          echo "Deploying prodcution for ${{ github.ref_name }}"
          echo "Deployed for tag ${{ github.ref_name }}"
        env:
          #CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          #CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_API_TOKEN: "iuSuGjPW41MP52ZpxlyY6ABSSbWbAGvIfuhTP91K"
          CLOUDFLARE_ACCOUNT_ID: "e0e0323ad86f07e674d7e74991733f0e"
